id: P008243
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14550
  title: རྨ་ཆུའི་བསམ་གཏན་གྱི་རྩོམ་བཏུས། བོད་ལ་ལྟ་བ།
  author: ''
  volumes:
    9417282d7f2c449aaf2d38f09678b62f:
      image_group_id: I1KG15700
      title: ''
      volume_number: 1
      total_pages: 168
