id: P008243
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 13:10:14.193363
source_metadata:
  id: bdr:W1KG14550
  title: རྨ་ཆུའི་བསམ་གཏན་གྱི་རྩོམ་བཏུས། བོད་ལ་ལྟ་བ།
  author: ''
  volumes:
    9417282d7f2c449aaf2d38f09678b62f:
      image_group_id: I1KG15700
      title: ''
      volume_number: 1
      total_pages: 168
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
